import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: { 
    flex: 1, 
    backgroundColor: '#f8fafc',
  },
  scrollContainer: {
    flex: 1,
  },
  navegacaoContainer: {
    backgroundColor: '#0284c7',
  },
  heroSection: {
    backgroundColor: '#0284c7',
    paddingBottom: 40,
  },
  heroBackground: {
    alignItems: 'center',
    padding: 30,
    paddingTop: 40,
  },
  logoContainer: {
    marginBottom: 20,
  },
  logoIcon: {
    width: 80,
    height: 80,
    borderRadius: 20,
    backgroundColor: '#0ea5e9',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#ffffff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  heroTitle: {
    fontSize: screenWidth < 768 ? 24 : 32,
    fontWeight: '800',
    color: '#ffffff',
    marginBottom: 12,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 4,
  },
  heroSubtitle: {
    fontSize: screenWidth < 768 ? 14 : 16,
    color: '#e0f2fe',
    textAlign: 'center',
    lineHeight: screenWidth < 768 ? 20 : 24,
    maxWidth: screenWidth < 768 ? '100%' : 600,
    paddingHorizontal: screenWidth < 768 ? 20 : 0,
  },
  statusSection: {
    backgroundColor: '#ffffff',
    marginHorizontal: screenWidth < 768 ? 16 : 20,
    marginTop: -20,
    padding: screenWidth < 768 ? 20 : 25,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  credenciamentoSection: {
    marginHorizontal: 20,
    marginTop: 20,
  },
  successBox: {
    backgroundColor: '#f0fdf4',
    padding: 20,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#22c55e',
    flexDirection: 'row',
    alignItems: 'center',
  },
  successText: {
    color: '#166534',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 12,
    flex: 1,
  },
  warningBox: {
    backgroundColor: '#fffbeb',
    padding: 20,
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#f59e0b',
    flexDirection: 'row',
    alignItems: 'center',
  },
  warningText: {
    color: '#92400e',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 12,
    flex: 1,
  },
  sectionTitle: {
    fontSize: 26,
    fontWeight: '700',
    color: '#0f172a',
    marginBottom: 8,
    textAlign: 'center',
  },
  sectionSubtitle: {
    fontSize: 16,
    color: '#64748b',
    textAlign: 'center',
    marginBottom: 35,
    lineHeight: 22,
  },
  refreshSection: {
    backgroundColor: '#ffffff',
    marginHorizontal: 20,
    marginTop: 20,
    padding: 25,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
    alignItems: 'center',
  },
  refreshButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#10b981',
    paddingHorizontal: 24,
    paddingVertical: 14,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  refreshButtonText: {
    color: '#ffffff',
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 8,
  },
  cadastrarContainer: {
    backgroundColor: '#ffffff',
    margin: 20,
    marginTop: 20,
    padding: 25,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  infoContainer: {
    marginTop: 20,
    padding: 20,
    backgroundColor: '#e0f2fe',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#bae6fd',
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0c4a6e',
    marginLeft: 12,
  },
  infoDescription: {
    fontSize: 14,
    color: '#075985',
    lineHeight: 22,
  },
  loadingContainer: {
    backgroundColor: '#ffffff',
    margin: 20,
    marginTop: 20,
    padding: 40,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#64748b',
    fontWeight: '500',
  },
  emptyStateContainer: {
    backgroundColor: '#ffffff',
    margin: 20,
    marginTop: 20,
    padding: 40,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyStateTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#0f172a',
    marginBottom: 8,
    textAlign: 'center',
  },
  emptyStateText: {
    fontSize: 16,
    color: '#64748b',
    textAlign: 'center',
    lineHeight: 22,
  },
  servicesSection: {
    backgroundColor: '#ffffff',
    marginHorizontal: 16,
    marginTop: 20,
    marginBottom: 40,
    paddingHorizontal: 16,
    paddingVertical: 25,
    borderRadius: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 3,
    overflow: 'visible',
  },
  mainContent: {
    flexDirection: screenWidth < 768 ? 'column' : 'row',
    gap: screenWidth < 768 ? 16 : 20,
    marginHorizontal: screenWidth < 768 ? 16 : 20,
    marginTop: 20,
    marginBottom: 40,
    minHeight: screenWidth < 768 ? 500 : 550,
  },
  responsiveContainer: {
    flex: 1,
    marginHorizontal: screenWidth < 768 ? 16 : 20,
    marginTop: 20,
    marginBottom: 40,
  },
  leftPanel: {
    flex: screenWidth < 768 ? 0 : 1,
    maxWidth: screenWidth < 768 ? '100%' : 400,
    width: screenWidth < 768 ? '100%' : undefined,
  },
  rightPanel: {
    flex: screenWidth < 768 ? 0 : 1.5,
    minWidth: screenWidth < 768 ? '100%' : 600,
    width: screenWidth < 768 ? '100%' : undefined,
    minHeight: screenWidth < 768 ? 350 : 400,
  },
  unifiedContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
    flex: 1,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  unifiedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9',
  },
  unifiedTitle: {
    fontSize: screenWidth < 768 ? 16 : 18,
    fontWeight: '700',
    color: '#0f172a',
    marginLeft: 8,
  },
  unifiedCardsContainer: {
    flex: 1,
  },
  unifiedCardsContent: {
    paddingHorizontal: 4,
  },
  unifiedCardsRow: {
    flexDirection: 'row',
    gap: screenWidth < 768 ? 12 : 16,
    paddingVertical: 8,
    justifyContent: screenWidth < 768 ? 'flex-start' : 'center',
  },
  unifiedCardWrapper: {
    backgroundColor: '#f8fafc',
    borderRadius: 12,
    padding: 0,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    width: screenWidth < 768 ? screenWidth - 100 : Math.min(340, (screenWidth - 200) / 2.5),
    flexShrink: 0,
    position: 'relative',
    overflow: 'hidden',
  },
  unifiedEmptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  unifiedEmptyTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#64748b',
    marginTop: 16,
    marginBottom: 8,
    textAlign: 'center',
  },
  unifiedEmptyText: {
    fontSize: 14,
    color: '#94a3b8',
    textAlign: 'center',
    lineHeight: 20,
    maxWidth: 300,
  },
  selectedServiceContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
  },
  selectedServiceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    gap: 12,
  },
  selectedServiceTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#0f172a',
  },
  noSelectionContainer: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 40,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 5,
    minHeight: 400,
  },
  noSelectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#64748b',
    marginTop: 16,
    marginBottom: 12,
    textAlign: 'center',
  },
  noSelectionText: {
    fontSize: 16,
    color: '#94a3b8',
    textAlign: 'center',
    lineHeight: 24,
    maxWidth: 300,
  },
  draggedCardsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  draggedCardsTitle: {
    fontSize: screenWidth < 768 ? 16 : 18,
    fontWeight: '700',
    color: '#0f172a',
    marginLeft: 8,
  },
  clearButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fef2f2',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#fecaca',
  },
  clearButtonText: {
    fontSize: 12,
    color: '#dc2626',
    fontWeight: '600',
    marginLeft: 4,
  },
  draggedCardsContainer: {
    flex: 1,
    minHeight: screenWidth < 768 ? 300 : 350,
  },
  draggedCardsContent: {
    paddingHorizontal: 4,
  },
  draggedCardsRow: {
    flexDirection: 'row',
    gap: screenWidth < 768 ? 12 : 16,
    paddingVertical: 8,
    justifyContent: screenWidth < 768 ? 'flex-start' : 'center',
  },
  draggedCardWrapper: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 0,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    width: screenWidth < 768 ? screenWidth - 60 : Math.min(380, (screenWidth - 120) / 2.5),
    flexShrink: 0,
    position: 'relative',
    overflow: 'hidden',
  },
  removeButtonTop: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: '#fef2f2',
    borderRadius: 6,
    padding: 4,
    borderWidth: 1,
    borderColor: '#fecaca',
    zIndex: 10,
  },
});

export default styles;
